### ISSUE TITLE
如果说要再这里面使用electron的模块应该怎么玩啊

### ISSUE THREAD

**Issue by sqwm** [zhangshuaidan/umi-electron#1]

**Comment by Dan-0216** [comment]
主进程的入口文件放在app/main/index.js中，你可以在这里面进行主进程的业务逻辑，你说的electron意思是在渲染进程中使用吗？

**Comment by sqwm** [comment]
import { remote } from 'electron' 
我想在渲染进程中调用这个remote模块 =。= 现在我直接调用的话 是会报错的

**Comment by sqwm** [comment]
> 主进程的入口文件放在应用程序/主/ index.js中，你可以在这里面进行主进程的业务逻辑，你说的电子意思是在渲染进程中使用吗？
就是我应该如何正确使用import { remote } from 'electron'
在src目录下

**Comment by Dan-0216** [comment]
> > 主进程的入口文件放在应用程序/主/ index.js中，你可以在这里面进行主进程的业务逻辑，你说的电子意思是在渲染进程中使用吗？
> > 就是我应该如何正确使用import { remote } from 'electron'
> > 在src目录下
已提交最新版本的代码,请重新拉取代码试一下。
